### ISSUE TITLE
step07: Maze emoji is not rendering properly on Mac

### ISSUE THREAD

**Issue by sahajre** [danicat/pacgo#1]
On MacOS 10.14.4, step 07, the maze rendering is distorted.

![](https://pbs.twimg.com/media/D38HwEEU0AApb0Y.jpg)

**Comment by sahajre** [comment]
The issue can be fixed by adding space after `wall` and `dot` emoji in `config.json`.

```
{
    ...,

    "wall": "🌵 ",
    "dot": "🧀 ",

    ...
}
```
![](https://pbs.twimg.com/media/D38Hy2vUIAAH7xb.jpg)

**Comment by sahajre** [comment]
To clarify further, the rendering problem observed while using iTerm2 (Build 3.1.5). 

The original code works properly (without any changes) in Terminal 2.9.4.

**Comment by danicat** [comment]
Thanks for reporting this. I did develop this using both Linux and Mac, and only have faced a similar issue on the VS Code built-in terminal. I wonder if inserting the extra space will break the terminals that current work. I don't have the energy now, but I'll test this as soon as possible.

**Comment by danicat** [comment]
I'm closing this as there is an available workaround and nobody else seem to be affected by this issue.
