### ISSUE TITLE
Pac Go with katacoda scenarios

### ISSUE THREAD

**Issue by ysaito8015** [danicat/pacgo#14]
step07,08 still work in progress...

https://www.katacoda.com/ysaito/courses/pacgo-walkthrough

**Comment by danicat** [comment]
Awesome work! Thanks for sharing.

If you want, you may submit a PR amending the README.md adding a "Links" session to the end with your katacoda on it.

**Comment by danicat** [comment]
Closing as there is nothing really to be done. :)
