### ISSUE TITLE
Please include screenshots of the game in the README!

### ISSUE THREAD

**Issue by Naereen** [danicat/pacgo#15]
Hi!
Your project seems very cool and all, but without any screenshots of the game in the README, I don't see how people could trust that your game works and that it has emojis etc ;-)
Thanks!

**Comment by danicat** [comment]
Maybe it could be an improvement, but believe me, people trust :)

These are the recordings of some of the times I've presented it in public.

https://youtu.be/SM8LTMnB4x0
https://youtu.be/0qvW4kIlS8I
https://youtu.be/SM8LTMnB4x0

Nevertheless, it's hacktober fest. If you want to submit a PR to fix this please go ahead. :)

**Comment by Ghostom998** [comment]
@Naereen be the change you want to see :)

**Comment by Naereen** [comment]
Well I did it, don't really know why, it's @danicat's project…
Regards.

**Comment by danicat** [comment]
@Naereen it's not really my project anymore. I mean, I'll be the benevolent dictator for life for this project, but it's open source with a MIT license, which means is not only mine, is for the whole community.

Maybe you would find interesting researching a bit more about open source culture :)

**Comment by danicat** [comment]
Closed by #17.
