### ISSUE TITLE
Works on which terminal

### ISSUE THREAD

**Issue by pepa65** [danicat/pacgo#25]
What environment is necessary to make this work? I tried various terminals, with varying results, but none of them will run this game (go-running the main.go from Step 9).

* go version go1.13.1 linux/amd64
* tried MATE Terminal (colourful, no movement, no player/ghosts), Sakura (similar), xvt (instant game over, no nice graphics), alacritty (flashes, no black & white graphics).

**Comment by danicat** [comment]
I'm adding a help wanted label as currently I don't have a Linux machine to test it.

**Comment by rpoe** [comment]
For me it works on an Android tablet in the Termux app.
