### ISSUE TITLE
Make the source code godoc friendly

### ISSUE THREAD

**Issue by danicat** [danicat/pacgo#29]
This project on godoc doesn't look very nice. Maybe we could do something about it by creating doc.go files for each step.

**Comment by nasirhm** [comment]
@danicat I would like to take this issue and make it godoc friendly.

**Comment by danicat** [comment]
Sure, feel free to work on this. The original idea was to make sure that when someone sees the package documentation on godoc.org they would actually see the tutorial content. Probably adding a doc.go file to each of the steps with the instructions would work, but then it would mean duplicating a lot of text, which I'm not very happy about it. I'm not sure if there is a good solution out of this dilemma.

**Comment by nasirhm** [comment]
@danicat Makes sense, repeating alot of text can be messy, I think we need to think of some innovative way to tackle this. What do you think what else we can do for it ?

**Comment by nasirhm** [comment]
How about creating an Additional branch which is godoc friendly, that I can maintain, That way the `master` branch wouldn't get overloaded by huge amount of repetitive text. I hope godoc provides the ability to point at some other branch than master. If not, I can fork it an maintain the godoc source code there?

**Comment by nasirhm** [comment]
I've got an idea, How about making the source code godoc friendly for the github and adding the link to the "Future Codelab" if someone wants to do it step by step, That would mean removing it from the .md files, What do you think ?
