### ISSUE TITLE
runtime error: index out of range when makeMove()

### ISSUE THREAD

**Issue by CaoGongHui** [danicat/pacgo#36]
Environment :
go version go1.16.2 linux/amd64 
In wsl2 Ubuntu20.04

In ##step03##, when I move the 'P' to this position, the program panics an error like the title.
![image](https://user-images.githubusercontent.com/30141595/140901565-5534855e-a9e7-4bc3-9732-78746c328bb4.png)

I print the logs in function ```makeMove()```
```go
       rest code
       ----
	case "LEFT":
		newCol = newCol - 1
		if newCol < 0 {
			newCol = len(maze[0]) - 1
		}
	}
	log.Println("len of maze: ", len(maze))
	log.Println("len of maze[0]: ", len(maze[0]))
	log.Println("newRow: %d\n", newRow)
	log.Println("newCol: %d\n", newCol)
	if maze[newRow][newCol] == '#' {          //This is line 124
		newRow = oldRow
		newCol = oldCol
	}
    ----
    rest code
```
then It prints the message  below
```
2021/11/09 17:48:25 len of maze:  24
2021/11/09 17:48:25 len of maze[0]:  28
2021/11/09 17:48:25 newRow: %d
 11
2021/11/09 17:48:25 newCol: %d
 27
panic: runtime error: index out of range [27] with length 22

goroutine 1 [running]:
main.makeMove(0xb, 0x0, 0x4e3d37, 0x4, 0xb, 0x0)
        /mnt/e/github/pacgodemo/main.go:124 +0x37c
main.movePlayer(...)
        /mnt/e/github/pacgodemo/main.go:135
main.main()
        /mnt/e/github/pacgodemo/main.go:183 +0x145
exit status 2
```
I don't know why the length is 22.
Anyone else can help me? Thanks

**Comment by danicat** [comment]
Can you please check that the len of line 11 is the same of line zero? The problem you are facing is that probably your maze doesn't have the space characters filling the empty space on the other size of the maze. The way the code was written it relies on the TXT file for the maze to be uniform.

In summary, after the last # on line 11 make sure the rest of the line is filled with spaces.

**Comment by CaoGongHui** [comment]
@danicat 
Thanks for your

**Comment by CaoGongHui** [comment]
@danicat 
Thanks for your detailed explanation. Forgive my naive issue.
I have resolved by unable the trimTrailingWhitespace function of vs code.
