### ISSUE TITLE
go mod files are missing

### ISSUE THREAD

**Issue by rpoe** [danicat/pacgo#37]
For the latest go version libraries need to have a go mod file for dependency management.
Found by calling in directory step02 
go run main.go
output:
main.go:10:2: no required module provides package github.com/danicat/simpleansi: go.mod file not found in current directory or any parent directory; see 'go help modules'

**Comment by rpoe** [comment]
Attached is the fix for this issue. Please integrate or create a branch, where I can commit. (I do not have the permission. Thanks[

fix_issue#37.zip](https://github.com/danicat/pacgo/files/8238031/fix_issue.37.zip)

**Comment by danicat** [comment]
The contribution model for this project is to submit a pull request (PR). You can't commit to the core project, but you can fork it to your own Github account, make your changes and open a PR to this repo for review.

That said go.mod support is coming in the next version which I'm working on - see branches `step00`, `step01` and so on... albeit it has been slow progress so far. I'm more than happy to update the current version if you send a PR.

**Comment by danicat** [comment]
Fixed by #41
