### ISSUE TITLE
Document in Step 10 should use `ghost` instead of `Ghost`

### ISSUE THREAD

**Issue by prithvijj** [danicat/pacgo#43]
## Context

I was following through the tutorial, just to refresh my memory on `Go` and while reaching to the end of the `README.md` for `Step 10`, 

https://github.com/danicat/pacgo/blob/2cf44cccb9a8e8453c045baa3e9818cef64d6a98/step10/README.md?plain=1#L140-L146

Found that it should use the type `ghost` instead of `Ghost` since the type does not exist,

The code within `main.go` for `Step 10` is fine, but yeah just a small typo I noticed

https://github.com/danicat/pacgo/blob/2cf44cccb9a8e8453c045baa3e9818cef64d6a98/step10/main.go#L253-L259

## Issue

Change from `ghosts []*Ghost` to `ghosts []*ghost` within `README.md` for `Step 10`
https://github.com/danicat/pacgo/blob/2cf44cccb9a8e8453c045baa3e9818cef64d6a98/step10/README.md?plain=1#L140-L146

Code equivalent in `main.go` for `Step 10`
https://github.com/danicat/pacgo/blob/2cf44cccb9a8e8453c045baa3e9818cef64d6a98/step10/main.go#L253-L259

**Comment by danicat** [comment]
Closed by #44
